"use strict";

const { createClient } = require("@supabase/supabase-js");
const crypto = require("crypto");

const getKey = ({ directory, file }) => {
  // Use the hash and extension generated by Strapi to ensure uniqueness and correct file type
  return `${directory}/${file.hash}${file.ext}`.replace(/^\//g, "");
};

module.exports = {
  provider: "supabase",
  name: "Supabase Storage (Production Ready)",
  auth: {
    apiUrl: {
      label: "Supabase API Url",
      type: "text",
    },
    apiKey: {
      label: "Supabase API Key",
      type: "text",
    },
    bucket: {
      label: "Supabase storage bucket",
      type: "text",
    },
    directory: {
      label: "Directory inside Supabase storage bucket",
      type: "text",
    },
    options: {
      label: "Supabase client additional options",
      type: "object",
    },
  },
  init: (config) => {
    const apiUrl = config.apiUrl;
    const apiKey = config.apiKey;

    const bucket = config.bucket || "strapi-uploads";
    const directory = (config.directory || "").replace(/(^\/)|(\/$)/g, "");
    const options = config.options || {};

    const supabase = createClient(apiUrl, apiKey, options);

    const upload = (file) =>
      new Promise((resolve, reject) => {
        if (!file.hash) {
          file.hash = crypto.createHash("md5").update(file.name).digest("hex");
        }

        const fileKey = getKey({ directory, file });
        const buf = file.buffer || file.stream;

        supabase.storage
          .from(bucket)
          .upload(fileKey, Buffer.from(buf, "binary"), {
            cacheControl: "public, max-age=31536000, immutable",
            upsert: true,
            contentType: file.mime,
          })
          .then(({ data, error: error1 }) => {
            if (error1) return reject(error1);

            // Handle both Supabase SDK v1 and v2 formats
            const result = supabase.storage.from(bucket).getPublicUrl(fileKey);
            const publicURL = result.data?.publicUrl || result.publicURL;

            if (!publicURL) {
              return reject(new Error("Could not retrieve public URL from Supabase"));
            }

            file.url = publicURL;
            resolve();
          })
          .catch((err) => reject(err));
      });

    return {
      upload,
      uploadStream: upload, // Strapi 5 uses uploadStream for better performance
      delete: (file) =>
        new Promise((resolve, reject) => {
          supabase.storage
            .from(bucket)
            .remove([getKey({ directory, file })])
            .then(({ data, error }) => {
              if (error) return reject(error);
              resolve();
            })
            .catch((err) => reject(err));
        }),
    };
  },
};
